vault:
  rows: 6
  max-vaults: 3
  save-format: yaml
  auto-save: true
  messages:
    open: "&aOpening vault #%number%..."
    invalid-number: "&cInvalid vault number."
    too-many: "&cYou do not have access to that many vaults."