name: PlayerVaults
version: '1.0-SNAPSHOT'
main: org.brokeski.playerVaults.PlayerVaults
api-version: '1.21'
authors: [ Real6000 ]
description: Basic player vault for lego game
commands:
  vault:
    description: Open your player vault
    usage: /vault
    permission: playervaults.use
  vaults:
    description: Open vault selection GUI
    usage: /vaults
    permission: playervaults.use
permissions:
  playervaults.use:
    default: true
  playervaults.admin:
    default: op